[package]
name = "day09-2018"
version = "0.1.0"
authors = ["Barret Rennie <barret@brennie.ca>"]
edition = "2018"

[[bin]]
name = "day09-2018"
path = "src/main.rs"

[dependencies]
structopt = "0.2.14"
