[package]
name = "day19-2020"
version = "0.1.0"
authors = ["Barret Rennie <barret@brennie.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
combine = "4.4.0"
itertools = "0.9.0"
regex = "1.4.2"
