[package]
name = "day05"
version = "0.1.0"
authors = ["Barret Rennie <barret@brennie.ca>"]
edition = "2018"

[lib]
name = "day05"
path = "src/lib.rs"

[[bin]]
name = "part1"
path = "src/part1.rs"

[dependencies]
